name: build-book
on:
  workflow_dispatch: 

jobs:
  build-book:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape texlive texlive-font-utils texlive-fonts-recommended texlive-latex-extra golang-go
      - name: Build the book
        run: |
          bash make.sh
      - name: Upload the book
        uses: actions/upload-artifact@v7
        with:
          path: out/*_release.pdf
          archive: false
